<?php

return [
    'max_suggestions' => 5,
    'max_levenshtein_distance' => 3,
    'length_tolerance' => 2,
    /** Multiplier for ContextAwarenessService score when ranking (higher = more sentence-context influence). */
    'context_weight' => (float) env('SPELLING_CONTEXT_WEIGHT', 1.35),
    'languages' => ['english', 'tagalog', 'taglish'],
    'use_thesaurus' => env('SPELLING_USE_THESAURUS', true),
    'auto_seed_dictionary' => env('SPELLING_AUTO_SEED_DICTIONARY', true),
    'direct_corrections' => [
        // Core phrase joins / splits
        'pba' => 'pa ba',
        'poba' => 'po ba',
        'koba' => 'ko ba',
        'ikawba' => 'ikaw ba',
        'pedeba' => 'puwede ba',
        'pwdeba' => 'puwede ba',
        'pwdba' => 'puwede ba',
        'diko' => 'hindi ko',
        'dikona' => 'hindi ko na',
        'dikopa' => 'hindi ko pa',
        'dika' => 'hindi ka',
        'dikaba' => 'hindi ka ba',
        'dikayo' => 'hindi kayo',
        'dikoalam' => 'hindi ko alam',
        'dimo' => 'hindi mo',
        'dinya' => 'hindi niya',
        'dila' => 'hindi nila',
        'salamatpo' => 'salamat po',
        'bukasna' => 'bukas na',
        'nasaanka' => 'nasaan ka',
        'wagmo' => 'huwag mo',
        'wagkana' => 'huwag ka na',
        'knaba' => 'ka na ba',
        'oklang' => 'okay lang',
        'ayawko' => 'ayaw ko',
        'kainna' => 'kain na',
        'inomna' => 'inom na',
        'alisna' => 'alis na',
        'labasna' => 'labas na',
        'pasokna' => 'pasok na',
        'uwina' => 'uwi na',
        'projectko' => 'project ko',
        'assignmentko' => 'assignment ko',
        'examko' => 'exam ko',
        'quizko' => 'quiz ko',
        'gradeko' => 'grade ko',
        'scoreko' => 'score ko',
        'mag co compute' => 'mag-co-compute',
        'mag co-compute' => 'mag-co-compute',
        'mag la login' => 'magla-login',
        'mag la-login' => 'magla-login',
        'mag la login muna ako' => 'magla-login muna ako',
        'mag u update' => 'mag-u-update',
        'mag u-update' => 'mag-u-update',
        'magco compute' => 'mag-co-compute',
        'co compute' => 'co-compute',
        'coompute' => 'compute',
        'gena' => 'gen alpha',
        'genb' => 'gen beta',
        'fr fr' => 'frfr',
        'no cap' => 'nocap',
        'hirapnmn' => 'hirap naman',
        'bakitnmn' => 'bakit naman',
        'werka' => 'where are you',

        // Chat / social media typos
        'napo' => 'na po',
        'opo' => 'o po',
        'den' => 'din',
        'ren' => 'rin',
        'dto' => 'dito',
        'd2' => 'dito',
        'jan' => 'diyan',
        'jn' => 'diyan',
        'dun' => 'doon',
        'don' => 'doon',
        'd3' => 'doon',
        'san' => 'saan',
        'saan2' => 'saan-saan',
        'kelan' => 'kailan',
        'keln' => 'kailan',
        'bkit' => 'bakit',
        'bkt' => 'bakit',
        'bat' => 'bakit',
        'pano' => 'paano',
        'panoo' => 'paano',
        'pno' => 'paano',
        'panu' => 'paano',
        'anu' => 'ano',
        'anoo' => 'ano',
        'cno' => 'sino',
        'sinoo' => 'sino',
        'sna' => 'sana',
        'snaa' => 'sana',
        'pra' => 'para',
        'para2' => 'para-paraan',
        'plang' => 'pa lang',
        'palang' => 'pa lang',
        'nmn' => 'naman',
        'namn' => 'naman',
        'nman' => 'naman',
        'lng' => 'lang',
        'langg' => 'lang',
        'tlga' => 'talaga',
        'talga' => 'talaga',
        'tlagaa' => 'talaga',
        'wag' => 'huwag',
        'wag na' => 'huwag na',
        'kna' => 'ka na',
        'kpa' => 'ka pa',
        'kaht' => 'kahit',
        'khit' => 'kahit',
        'kht' => 'kahit',
        'kc' => 'kasi',
        'kse' => 'kasi',
        'ksi' => 'kasi',
        'kase' => 'kasi',
        'cge' => 'sige',
        'cgeh' => 'sige',
        'sge' => 'sige',
        'ge' => 'sige',
        'okey' => 'okay',
        'ok lng' => 'okay lang',
        'okies' => 'okay',

        // Filipino typos
        'kumosta' => 'kumusta',
        'musta' => 'kumusta',
        'slamats' => 'salamat',
        'slamat' => 'salamat',
        'pasenya' => 'pasensya',
        'sensya' => 'pasensya',
        'intindiin' => 'intindihin',
        'intnde' => 'intindi',
        'subra' => 'sobra',
        'sobrahan' => 'sobrang',
        'sobranggg' => 'sobrang',
        'masyado' => 'masyadong',
        'masiado' => 'masyadong',
        'siguroo' => 'siguro',
        'pede' => 'puwede',
        'pwede' => 'puwede',
        'pwde' => 'puwede',
        'pede ba' => 'puwede ba',
        'pede po' => 'puwede po',
        'meron' => 'mayroon',
        'merun' => 'mayroon',
        'meronn' => 'mayroon',
        'walaa' => 'wala',
        'wla' => 'wala',
        'wlaa' => 'wala',
        'gsto' => 'gusto',
        'gustu' => 'gusto',
        'ayoko' => 'ayaw ko',
        'dikita' => 'hindi kita',
        'hndi' => 'hindi',
        'ndi' => 'hindi',
        'hnd' => 'hindi',
        'gnun' => 'ganoon',
        'ganun' => 'ganoon',
        'ganern' => 'ganoon',
        'ngaun' => 'ngayon',
        'ngyon' => 'ngayon',
        'mamaya2' => 'mamaya-maya',
        'mamya' => 'mamaya',
        'mamyaa' => 'mamaya',
        'bukass' => 'bukas',
        'kahpon' => 'kahapon',
        'khapon' => 'kahapon',
        'kaninaa' => 'kanina',
        'kanina2' => 'kanina',
        'andto' => 'andito',
        'andyan' => 'andiyan',
        'nsa' => 'nasa',
        'nsaan' => 'nasaan',
        'nako' => 'naku',
        'nakoo' => 'naku',
        'teka2' => 'teka-teka',
        'sandli' => 'sandali',
        'sandale' => 'sandali',
        'konti' => 'kaunti',
        'unti' => 'kaunti',
        'marame' => 'marami',
        'madami' => 'marami',
        'mdmi' => 'marami',
        'pagkaen' => 'pagkain',
        'uwian' => 'uwian',
        'trabaho2' => 'trabaho',
        'skwela' => 'eskuwela',
        'schoolnmn' => 'school naman',

        // English typos common in Taglish
        'recieve' => 'receive',
        'recieved' => 'received',
        'seperate' => 'separate',
        'seperete' => 'separate',
        'definately' => 'definitely',
        'definitly' => 'definitely',
        'definitley' => 'definitely',
        'enviroment' => 'environment',
        'goverment' => 'government',
        'embarass' => 'embarrass',
        'occassion' => 'occasion',
        'succesful' => 'successful',
        'sucessful' => 'successful',
        'succes' => 'success',
        'sucess' => 'success',
        'wich' => 'which',
        'wat' => 'what',
        'wer' => 'where',
        'wer u' => 'where are you',
        'gud' => 'good',
        'gudmorning' => 'good morning',
        'gudnyt' => 'good night',
        'tnx' => 'thanks',
        'thanx' => 'thanks',
        'thnx' => 'thanks',
        'pls' => 'please',
        'plss' => 'please',
        'asap' => 'as soon as possible',
        'alryt' => 'alright',
        'ryt' => 'right',
        'rily' => 'really',
        'realy' => 'really',
        'tom' => 'tomorrow',
        'tommorow' => 'tomorrow',
        'febuary' => 'february',
        'janurary' => 'january',

        // School / formal writing typos
        'alot' => 'a lot',
        'in able' => 'enable',
        'could of' => 'could have',
        'should of' => 'should have',
        'would of' => 'would have',
        'loose' => 'lose',
        'losee' => 'lose',
        'becuase' => 'because',
        'ocassionally' => 'occasionally',
        'adress' => 'address',
        'acommodate' => 'accommodate',
        'accomodate' => 'accommodate',
        'youre' => "you're",
        'theyre' => "they're",

        // Extra high-impact classroom / chat shortcuts
        'dko' => 'hindi ko',
        'wla' => 'wala',
        'kmi' => 'kami',
        'ung' => 'ang',
        'nyo' => 'ninyo',
        'sbhin' => 'sabihin',
        'maintndhan' => 'maintindihan',
        'prng' => 'parang',
        'kya' => 'kaya',
        'kba' => 'ka ba',
        'grbe' => 'grabe',
        'actvty' => 'activity',
        'net' => 'internet',
    ],

    /*
    | Learned lexemes: after this many accepts (POST /api/vocabulary/learn), treat as dictionary-correct.
    */
    'learned_lexeme_auto_accept_min' => (int) env('SPELLING_LEARNED_MIN', 5),

    /*
    | Never flag these as misspellings (informal / Gen slang). Pair with user learning API.
    */
    'accepted_slang_lexemes' => [
        'rizz', 'fr', 'frfr', 'bet', 'gyat', 'aura', 'npc', 'sigma', 'skibidi', 'slay', 'bussin',
        'drip', 'delulu', 'nocap', 'lowkey', 'highkey', 'brainrot', 'cap', 'based', 'cooked',
        'sus', 'stan', 'vibe', 'vibing', 'yeet', 'flex', 'itsgiving', 'iykyk', 'fyp', 'mewing', 'mid',
        'simp', 'cringe', 'goated', 'lit', 'sheesh', 'unc', 'ohio',
    ],

    /*
    | Heuristic next-word prediction (last-token and multi-token tail). LM/transformer can replace this later.
    */
    'prediction_seeds' => [
        'the' => ['mall', 'store', 'office', 'school', 'park', 'bank', 'hospital', 'library', 'market', 'party'],
        'to' => ['the', 'sleep', 'eat', 'see', 'work', 'school', 'home', 'a', 'go', 'be', 'fix'],
        'a' => ['lot', 'bit', 'little', 'friend', 'good', 'great', 'new', 'big', 'small', 'few'],
        'i' => ['am', 'was', 'have', 'will', 'think', 'need', 'want', 'like', 'know', 'can'],
        'ng' => ['grades', 'bahay', 'school', 'expenses', 'total', 'project', 'assignment', 'exam', 'pera', 'oras'],
        'ako' => ['ay', 'lang', 'rin', 'din', 'muna', 'na', 'pa', 'ng'],
    ],
    'prediction_bigrams' => [
        'going to the' => ['mall', 'store', 'office', 'school', 'park', 'party', 'beach'],
        'going to a' => ['party', 'meeting', 'wedding', 'concert', 'restaurant', 'doctor'],
        'mag co compute ako ng' => ['grades', 'expenses', 'total', 'assignment', 'project'],
        'mag co-compute ako ng' => ['grades', 'expenses', 'total', 'assignment', 'project'],
        'co compute ako ng' => ['grades', 'expenses', 'total', 'assignment', 'project'],
        'compute ako ng' => ['grades', 'expenses', 'total', 'assignment', 'project'],
        'ako ng' => ['grades', 'bahay', 'school', 'assignment', 'pera', 'oras', 'ginagawa'],
    ],

    /*
    | Base costs for adapted Levenshtein (insert / delete / default substitute).
    | Per-pair substitute overrides still come from typo_patterns when present.
    */
    'edit_costs' => [
        'insert' => 1.0,
        'delete' => 1.0,
        'substitute' => 1.0,
    ],
];
